import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import { useGlobalStore } from '../components/store';
import styles from '../styles/Home.module.css';

const Home = () => {
    const token = useGlobalStore(state => state.accessToken);
    const loadLocalToken = () => {
        const token = localStorage.getItem('accessToken');
        return token;
    }
    const setToken = (newToken) => useGlobalStore.setState({accessToken: newToken});

    // client-side effect, because server cannot access localStorage.
    useEffect(() => {

        if (token === "none") {
            setToken(loadLocalToken());
        }
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    selamat datang di toko rotiku
                </h1>
                <p>{token}</p>

                <div className={styles.grid}>
                    <div className={styles.card}>
                    <h2>yuk login &rarr;</h2>
                    <form>
                        <label for="username"> Username: </label>
                        <input type="text" name="username"/>
                        <label for="email"> E-mail: </label>
                        <input type="text" name="email"/>
                        <label for="password"> Password: </label>
                        <input type="password" name="password"/>
                        <input type="submit" />
                    </form>
                    </div>
                </div>
                <p> atau daftar akun dulu...</p>
            </main>

            <footer className={styles.footer}>
                Tugas Khusus Webdev - BETIS 2023
            </footer>
        </div>
  )
}

export default Home;
